datepicker
gloomy-onion/Looking pull request #4
Opened 2024-03-12 10:52 UTC by gloomy-onion

2024-04-02 15:22 UTC, Alterqq commented on src/ui-kit/Checkbox/Checkbox.tsx
> +export const Checkbox = ({ checkboxType = 'checkbox', label = 'checkbox' }: CheckboxProps) => {
зачем лейблу дефолтное значение? а если я хочу просто чекбокс без него?

2024-04-02 15:22 UTC, Alterqq commented on src/ui-kit/DatePicker/DatePicker.module.scss
> +
Приттером надо пройтись

2024-04-02 15:22 UTC, Alterqq commented on src/ui-kit/DatePicker/DatePicker.tsx
> +registerLocale('ru', ru);
А что эта штука делает?

2024-04-02 15:22 UTC, Alterqq commented on src/ui-kit/DatePicker/styles.css
> +    font-family: Montserrat sans-serif rgba(31, 32, 65, 0.5);
давай попробуем через
:global {
  /* ... */
}
и перевести на scss, чтоб до переменных дотянуться

2024-04-02 15:22 UTC, Alterqq commented on src/ui-kit/Dropdown/Dropdown.module.scss
> +  width: 322px;
ширина должна ограничиваться внешним контейнером

2024-04-02 15:22 UTC, Alterqq commented on src/ui-kit/Dropdown/DropdownContainer.tsx
>    const toggleDropDown = () => {
Давай еще добавим функционал onClickOutside
чтоб у нас дропдаун закрывался при клике вне

2024-04-02 15:45 UTC, Alterqq requested changes

2024-04-02 15:45 UTC, Alterqq commented on package.json
> +    "date-fns": "^3.6.0",
удалить

2024-04-02 15:45 UTC, Alterqq commented on package.json
> +    "@babel/runtime": "^7.24.0",
удалить, но проверить, что работает

2024-04-02 15:45 UTC, Alterqq commented on src/ui-kit/Checkbox/Checkbox.module.scss
> +  background: linear-gradient(180deg, rgba(188, 156, 255, 1) 0%, rgba(139, 164, 249, 1) 100%) border-box;
подменить на переменные

2024-04-02 15:45 UTC, Alterqq commented on src/ui-kit/DatePicker/styles.css
> +    font-family: Montserrat sans-serif rgba(31, 32, 65, 0.5);
https://stackoverflow.com/questions/43613619/what-does-global-colon-global-do

2024-04-02 15:45 UTC, Alterqq commented on src/ui-kit/Dropdown/Dropdown.module.scss
> +  width: 322px;
на странице оберни дивом с инлайн стилями

2024-04-02 15:45 UTC, Alterqq commented on src/ui-kit/helpers.tsx
>  export const getLabelColor = (buttonType: string) =>
разнести хелперы по местам использования в файлики

2024-04-02 19:20 UTC, gloomy-onion commented on src/ui-kit/DatePicker/styles.css
> +    font-family: Montserrat sans-serif rgba(31, 32, 65, 0.5);
не сработало

2024-04-03 07:12 UTC, Alterqq approved these changes

2024-04-03 08:46 UTC, merged